name: Build and Test - Pixi

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/website/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/website/**"

jobs:
  run_c:
    name: C++ - Build/Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14] # macos-14 is macSilicon
    steps:
      - name : Setup repo
        uses: actions/checkout@v4

      - name : Remove Mono framework
        if: runner.os == 'macOS'
        run:
          sudo rm -rf /Library/Frameworks/Mono.framework
          sudo pkgutil --forget com.xamarin.mono-MDK.pkg
          sudo rm /etc/paths.d/mono-commands

      - name : Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
          cache: true

      - name: C++ - Build and Test
        shell: bash
        run: pixi run run_c

  run_python:
    name: Python - Build/Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14] # macos-14 is macSilicon
    steps:
      - name : Setup repo
        uses: actions/checkout@v4

      - name : Remove Mono framework
        if: runner.os == 'macOS'
        run:
          sudo rm -rf /Library/Frameworks/Mono.framework
          sudo pkgutil --forget com.xamarin.mono-MDK.pkg
          sudo rm /etc/paths.d/mono-commands

      - name : Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
          cache: true

      - name: Python - Build and Test
        shell: bash
        run: pixi run run_python

      - name: Test Python Notebooks
        shell: pixi run bash {0}
        run: |
          # TODO: switch to Gen2 once testing data is available
          cd examples/Gen1/python_notebooks/
          # Install dependencies used by the notebooks
          pip3 install jupyter matplotlib tqdm pillow plotly

          # Running the notebooks
          jupyter nbconvert --execute --inplace dataprovider_quickstart_tutorial.ipynb
          jupyter nbconvert --execute --inplace mps_quickstart_tutorial.ipynb

      - name : Test python viewers
        shell: pixi run bash {0}
        run: |
          rerun analytics disable
          viewer_mps --vrs ./data/gen1/mps_sample/sample.vrs --mps_folder ./data/gen1/mps_sample/ --rrd_output_path viewer_mps.rrd
